### ISSUE TITLE
Servo declarado como Radar_Servo mas usado posteriormente como Sonar_Servo

### ISSUE THREAD

**Issue by rodrigossilveira** [BrinoOficial/Sonar#1]
Tem uma pequena confusão no nome declarado para o servo motor no código do arduino, que é Radar_Servo na linha 19 quando o objeto Servo é criado mas é usado como Sonar_Servo nas linhas 29, 36 e 53. Isso faz com que o sketch não compile porque Sonar_Servo não foi declarado em lugar nenhum.

**Comment by VictorRPacheco** [comment]
Muito obrigado! Acabei de realizar a correção do código
